version: '3'

services:
  app:
    image: ${DOCKER_ID_USER}/${APP_NAME}:${APP_VERSION}
    build:
      context: ..
      dockerfile: ${BUILD_DIR}/Dockerfile
    container_name: ${APP_NAME}
    network_mode: "host"
